spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    # 多数据库配置
    db1:
      driver-class-name: ${spring.datasource.driver-class-name}
      type: ${spring.datasource.type}
      jdbc-url: jdbc:mysql://172.20.169.133:3306/db1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
    db2:
      driver-class-name: ${spring.datasource.driver-class-name}
      type: ${spring.datasource.type}
      jdbc-url: jdbc:mysql://172.20.169.133:3306/db2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations: classpath*:com/example/demo/xml/*.xml

logging:
  level:
    com.example.demo.mapper: debug